version: '3.1'

services:
#database engine service
  mysql_db:
    container_name: mysql_container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: cine
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on: 
      - mysql_db
    ports:
      - 8085:8080

  socios-back:
    build:
      context: ./backend
      args:
        - JAR_FILE=api-man-socios-mysql-0.0.1-SNAPSHOT.jar
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - mysql_db
    ports:
      - 8096-8099:8096
    restart: always